my_new_project:
    # Applies to all files under models/staging/
    staging:
        materialized: table
    # Applies to all files under models/prep/
    prep:
        materialized: table
    # Applies to all files under models/mart/
    mart:
        materialized: table
